### ISSUE TITLE
Dosnt resolve media DTGE

### ISSUE THREAD

**Issue by rasmusfjord** [display/Umbraco-courier-providers#1]
Hey :)

I just tested it on a 7.3.6 with latest courier installed and did a clean build of your repo, added the bin file to my stage/prod. Then i cleared my courier cache on both setups and restartet them. 

Tried to create a new grid page, inserted a DTGE with a default mediapicker in, and it didnt translate to the live ids. Am i missing something ? i would like to help and test here if i can.

**Comment by skttl** [comment]
I had the same problem, and would also like to help :)

**Comment by rasmusjp** [comment]
Which versions of Umbraco, Courier and DTGE are you using?

**Comment by rasmusfjord** [comment]
Umbraco 7.3.6 and DTGE 0.2.0

Med venlig hilsen

-----------------------------------------------
Rasmus Lykke Fjord
42 40 76 20
On 06-05-2016 08:44:29, Rasmus <notifications@github.com> wrote:
Which versions of Umbraco, Courier and DTGE are you using?

**Comment by rasmusfjord** [comment]
Hey Rasmus 

I hope you can help me on this, i just investigated it further, i tried looking at your code but think its abit above me.

The setup i have is a grid with DTGE, in my DTGE i pick a doctype called "filelist".

Inside the doctype I then have a Nested content where i can pick a media folder. 

The issue is that when i courier this from stage,, the mediaId is never translated to media ID on live.

Similar things happening is :
- If the mediaitem dosnt exists on Live it dosnt pick it up
- if the mediaitem actually exists it dosnt translate the correct ID.

I would really love to help out on this since we have a customer but i dont know where to start.

Are you comming to Skybrud for the umbraco meetup on this comming wedensday Rasmus? 

Hope you can help

**Comment by rasmusjp** [comment]
Hi Rasmus

I can see that @leekelleher has made some updates to the DTGE resolver in his [fork](https://github.com/leekelleher/umbraco-courier-dataresolvers), I would suggest you try using that instead.

**Comment by rasmusfjord** [comment]
Boom thx for the hint rasmus their edition worked.
